### ISSUE TITLE
Maybe new version of Eazfuscator?

### ISSUE THREAD

**Issue by yasha107** [HoLLy-HaCKeR/EazFixer#29]
I have a file that is partly obfuscated by Eazfuscator, these are the classes that appear in dnSpy
![image](https://user-images.githubusercontent.com/10366336/79092077-58491500-7d58-11ea-9b9a-f8a71e5618bd.png)

I have never seen them called like that so maybe it's a new version of the obfuscator?

**Comment by HoLLy-HaCKeR** [comment]
Those are the runtime types EazFuscator uses for it's string decoder (as seen in this example), resource/assembly decrypters and virtual machine. You haven't seen those names before because it's what they're called before name obfuscation is applied. If you use [EazDecode](https://github.com/HoLLy-HaCKeR/EazDecode/) on an obfuscated binary or if you simply do not apply name protection, you will see them.
