### ISSUE TITLE
Failed reflection resolving for .NET Core runtimes

### ISSUE THREAD

**Issue by Duskfall** [HoLLy-HaCKeR/EazFixer#4]
Thanks for this!
For string encryption I get this error
![image](https://user-images.githubusercontent.com/2528125/35129416-30ebb40c-fcc4-11e7-9923-b5d42f508e7f.png)

**Comment by HoLLy-HaCKeR** [comment]
Could you upload the sample you're testing on?

**Comment by Duskfall** [comment]
https://drive.google.com/file/d/1SXhRaZKmSwbwthJdghcS0zP19R1YKsFU/view?usp=sharing

**Comment by HoLLy-HaCKeR** [comment]
The problem occurs while resolving types through reflection, but I'm not sure why. 

Although, something else that I noticed is that I was unable to enumerate Assembly.DefinedTypes because it could not resolve System.Runtime (yet dnSpy has no problems with it). I did some checking and it turns out that it is a .NET Core dll. Perhaps the problem lies there.

**Comment by HoLLy-HaCKeR** [comment]
The real problem is probably that the tool uses .NET 4.6.x, while your DLL uses .NET Core 2.0. So, .NET will get confused while trying to resolve the referenced assembly and not look in the .NET Core assembly locations (`C:\Program Files\dotnet\shared\Microsoft.NETCore.App`). Adding a custom AssemblyResolver will probably fix it.

**Comment by Duskfall** [comment]
Cool that makes sense! If I have time, I'll try forking the project and add a custom resolver like this https://stackoverflow.com/questions/1561806/looking-for-net-assembly-in-a-different-place.
I have done something similar in the past though I don't really remember clearly, it has been like 3 years :P

**Comment by HoLLy-HaCKeR** [comment]
Don't worry, I'm on its. There will be a problem if the .NET Core runtimes aren't installed though.

**Comment by Duskfall** [comment]
I have already tried de4dot and also tried the different params but no luck.  :/ I managed to debug it with dnSpy and got it working that way :P Thanks anyway!

**Comment by HoLLy-HaCKeR** [comment]
Alright, glad to hear that :)

I'll keep this issue open, in case Harmony updates.

**Comment by alecrt** [comment]
Hi Holly, i've the very same problem on a .NET 3.5 dll
Could u suggest me a fix to try your library?

Thx!
A.

**Comment by HoLLy-HaCKeR** [comment]
Your assembly was probably protected with an older version of Eazfuscator. Try de4dot.

**Comment by atser** [comment]
![image](https://user-images.githubusercontent.com/47887775/53238150-99401f00-36a9-11e9-9e5b-ac7f2a1f0903.png)

Please, help me with an error. thank
https://drive.google.com/open?id=1pcAxZ1T7TmB2WsCwtyVPQycWADrlq0OT

**Comment by HoLLy-HaCKeR** [comment]
This is an issue related to reflection resolving, not a support thread.

**Comment by HoLLy-HaCKeR** [comment]
Closing since EazFixer now targets both .NET Framework 4.7.2 and .NET Core 3.1, and Harmony has been updated to v2.x.
